name: CI/CD
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - '.mergify.yml'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    name: Preliminary Checks
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history

      - name: Install Poetry
        run: pip install -r requirements.txt

      - name: Restore Development Environment
        run: poetry install

      - name: Check code is syntactically correct
        shell: bash
        run: poe compile

      - name: Format Check
        shell: bash
        run: poe format-check

      - name: Test with Coverage
        shell: bash
        run: |
          poe coverage
          poe coverage-report
          poe coverage-html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.sha }}
          path: htmlcov
          if-no-files-found: ignore
          overwrite: true

  test:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    runs-on: ${{ matrix.os }}
    name: Test on Python ${{ matrix.python-version }}, on ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install -r requirements.txt

      - name: Restore Development Environment
        run: poetry install

      # - name: Bundle test/hello_world.py to single PE file
      #   shell: bash
      #   run: cd tests/ && bash bundle_hello_world_to_pe.sh

      # - name: Extract EMBER features
      #   shell: bash
      #   run: cd tests/ && docker compose up

      - name: Test
        shell: bash
        run: poe test

  deploy:
     name: Deploy
     needs:
       - test
     uses: ./.github/workflows/deploy.yml
     secrets: inherit